//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CZBK.ItcastOA.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string id { get; set; }
        public Nullable<short> delFlag { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public string userPwd { get; set; }
    }
}
